name: Unit Tests
run-name: Running unit tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project
        uses: actions/checkout@v4
      - name: Installing python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Upgrading pip, setuptools, wheel and build
        run: python -m pip install --upgrade pip setuptools wheel build
      - name: Building package
        run: python -m build
      - name: Installing package
        run: pip install -e .
      - name: Running tests
        run: python -m unittest discover -v